tool(grafana): test/tooling to ensure dashboards are simplified/importable (#264)
# Description

When it comes to JSON for Grafana dashboards, it seems best practice to
remove a bunch of unnecessary pieces like the name of your personal
datasource, current variable selection, etc. This PR:
1. Introduces `make simplify-dashboards` to automate this tedious
process.
2. Adds a unit test to ensure authors run this command.

## Related Issue

## Checklist

- [x] I have read the [contributing
documentation](https://retina.sh/docs/contributing).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See
[this
documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)
on signing commits.
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

### `make simplify-dashboards`
```bash
$ make simplify-dashboards 
cd deploy/grafana/dashboards/ && go test . -tags=dashboard,simplifydashboard -v
=== RUN   TestOverwriteDashboards
    simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: clusters.json
    simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: dns.json
    simplify-grafana-overwrite_test.go:22: simplifying/overwriting dashboard: pod-level.json
--- PASS: TestOverwriteDashboards (0.02s)
PASS
ok      github.com/microsoft/retina/deploy/grafana/dashboards   0.019s
```

### Unit Test to Ensure Simplification
```bash
go test . -tags=dashboard -v
=== RUN   TestDashboardsAreSimplified
    simplify-grafana_test.go:24: verifying that dashboard is simplified: clusters.json
    simplify-grafana_test.go:31: ERROR: dashboard has not been simplified. Please run: make simplify-dashboards
    simplify-grafana_test.go:24: verifying that dashboard is simplified: dns.json
    simplify-grafana_test.go:24: verifying that dashboard is simplified: pod-level.json
--- FAIL: TestDashboardsAreSimplified (0.01s)
FAIL
FAIL    github.com/microsoft/retina/deploy/grafana/dashboards   0.018s
FAIL
```

## Additional Notes
Code added in this PR is put behind the go build tag `dashboard`, so
these files are not compiled in Retina binaries.

---------

Signed-off-by: Hunter Gregory <42728408+huntergregory@users.noreply.github.com>