fix: Clean up before building windows image for git checks (#1950)
# Description

Windows build is timing out with the error below. The GA runner is
running out of memory. Cleaning up before building the windows image
makes enough space for the image to be build successfully. This logic
was already introduced for the `
dev/v0.0.33-windows` branch here
https://github.com/microsoft/retina/pull/1935/files
 
`Build Agent Windows Images (windows, amd64, 2019)
System.IO.IOException: No space left on device :
'/home/runner/actions-runner/cached/_diag/Worker_20251124-112903-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle,
ReadOnlySpan1 buffer, Int64 fileOffset) at
System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush() at
GitHub.Runner.Common.HostTraceListener.WriteHeader(String source,
TraceEventType eventType, Int32 id) at
System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType,
Int32 id, String message) at GitHub.Runner.Worker.Worker.RunAsync(String
pipeIn, String pipeOut) at
GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[]
args) System.IO.IOException: No space left on device :
'/home/runner/actions-runner/cached/_diag/Worker_20251124-112903-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle,
ReadOnlySpan1 buffer, Int64 fileOffset)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean
flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source,
TraceEventType eventType, Int32 id)
at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType,
Int32 id, String message)
at GitHub.Runner.Common.Tracing.Error(Exception exception)
at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[]
args)
Unhandled exception. System.IO.IOException: No space left on device :
'/home/runner/actions-runner/cached/_diag/Worker_20251124-112903-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle,
ReadOnlySpan 1 buffer, Int64 fileOffset)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean
flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at System.Diagnostics.TraceSource.Flush()
at GitHub.Runner.Common.Tracing.Dispose(Boolean disposing)
at GitHub.Runner.Common.Tracing.Dispose()
at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
at GitHub.Runner.Common.TraceManager.Dispose()
at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
at GitHub.Runner.Common.HostContext.Dispose()
at GitHub.Runner.Worker.Program.Main(String[] args)`
## Related Issue

If this pull request is related to any issue, please mention it here.
Additionally, make sure that the issue is assigned to you before
submitting this pull request.

## Checklist

- [x] I have read the [contributing
documentation](https://retina.sh/docs/Contributing/overview).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See
[this
documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)
on signing commits.
- [ ] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [ ] I have followed the project's style guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

The github action workflow is succeeding
Also build the windows ltsc2019 agent image and used it to create a
capture. No issues found
<img width="1923" height="898" alt="image"
src="https://github.com/user-attachments/assets/3fa4f485-ab7e-4e46-807e-17cf9439be5f"
/>


## Additional Notes

This seems to be caused by an update to the base image for the ltsc2019
build

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more
information on how to contribute to this project.